[service]
name = "dealgrabber"
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT dealgrabberflask.app:app"

[cron]
[[jobs]]
schedule = "35 9,18 * * *"
command = "python dealgrabber/deal/check_available.py"

[[jobs]]
schedule = "35 9,18 * * *"
command = "python dealgrabber/deal/check_price.py"
