[service]
name = "dealgrabber"
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT dealgrabberflask.app:app"

[cron]
[[jobs]]
schedule = "0 0,6,12,18 * * *"
command = "python dealgrabber/deal/check_available.py"
[[jobs]]
schedule = "0 0,6,12,18 * * *"
command = "python dealgrabber/deal/check_price.py"