[service]
name = "dealgrabber"
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT dealgrabber-app.app:app"

[cron]
# Run check_available.py at 6 AM and 6 PM daily
[[jobs]]
schedule = "50 8,18 * * *"
command = "python dealgrabber/check_available.py"

# Run check_price.py at 6 AM and 6 PM daily
[[jobs]]
schedule = "50 8,18 * * *"
command = "python dealgrabber/check_price.py"
